version: "3"

networks:
  qnap-apps:
    driver: bridge

services:

  portainer:
    image: portainer/portainer-ce:2.15.1
    container_name: qnap-portainer
    hostname: portainer
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
    volumes:
      - /share/Container/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9000:9000"
    networks:
      - qnap-apps

  phddns:
    image: liukunup/phddns:5.2.0
    container_name: phddns
    hostname: phddns
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    mac_address: ${HSK_MAC_ADDR:?error}
    networks:
      - qnap-apps

  nextcloud:
    image: nextcloud:24-apache
    container_name: qnap-nextcloud
    hostname: nextcloud
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
      - USER_UID=1000
      - USER_GID=1000
      - NEXTCLOUD_ADMIN_USER=${MY_USERNAME:?error}
      - NEXTCLOUD_ADMIN_PASSWORD=${MY_PASSWORD:?error}
      - NEXTCLOUD_TRUSTED_DOMAINS=${NAS_DOMAIN:?error}
      - MYSQL_PASSWORD=${MYSQL_ROOT_PASSWORD:?error}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=root
      - MYSQL_HOST=mysql-main:3306
    volumes:
      - /share/Container/nextcloud/nextcloud:/var/www/html
      - /share/Container/nextcloud/apps:/var/www/html/custom_apps
      - /share/Container/nextcloud/config:/var/www/html/config
      - /share/Container/nextcloud/data:/var/www/html/data
      - /share/Container/nextcloud/theme:/var/www/html/themes/custom
      - /share/Cloud:/media/qnap
    ports:
      - "28080:80"
    links:
      - mysql-main
    depends_on:
      - mysql-main
    networks:
      - qnap-apps

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:10.8.5
    container_name: qnap-jellyfin
    hostname: jellyfin
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
      - PUID=1000
      - PGID=1000
      - JELLYFIN_PublishedServerUrl=${NAS_DOMAIN:?error}
    volumes:
      - /share/Container/jellyfin/library:/config
      - /share/Container/jellyfin/tvseries:/data/tvshows
      - /share/Public/Media:/data/movies
    ports:
      - "8096:8096"
      - "8920:8920"
      - "7359:7359/udp"
      - "1900:1900/udp"
    networks:
      - qnap-apps

  piwigo:
    image: lscr.io/linuxserver/piwigo:13.1.0
    container_name: qnap-piwigo
    hostname: piwigo
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
      - PUID=1000
      - PGID=1000
    volumes:
      - /share/Container/piwigo/config:/config
      - /share/Container/piwigo/gallery:/gallery
      - /share/Cloud/Gallery:/gallery/galleries
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "28081:80"
    depends_on:
      - mysql-main
    networks:
      - qnap-apps

  drawio:
    image: jgraph/drawio:20.5.0
    container_name: qnap-drawio
    hostname: drawio
    restart: always
    ports:
      - "28091:8080"
    networks:
      - qnap-apps

  gitea:
    image: gitea/gitea:1.17.3
    container_name: qnap-gitea
    hostname: gitea
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=mysql-main:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=${MYSQL_ROOT_PASSWORD:?error}
    volumes:
      - /share/Container/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "23000:3000"
      - "222:22"
    depends_on:
      - mysql-main
    networks:
      - qnap-apps

  grafana:
    image: grafana/grafana:latest
    container_name: qnap-grafana
    hostname: grafana
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
      - GF_SECURITY_ADMIN_USER=${MY_USERNAME:?error}
      - GF_SECURITY_ADMIN_PASSWORD=${MY_PASSWORD:?error}
    volumes:
      - /share/Container/grafana:/var/lib/grafana
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "24000:3000"
    user: root
    networks:
      - qnap-apps

  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: qnap-code-server
    hostname: code-server
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
      - PUID=1000
      - PGID=1000
      - PASSWORD=${MY_PASSWORD:?error}
      - SUDO_PASSWORD=${MY_PASSWORD:?error}
      - PROXY_DOMAIN=${NAS_DOMAIN:?error}
      - DEFAULT_WORKSPACE=/config/workspace
    volumes:
      - /share/Container/code-server/config:/config
    ports:
      - "28443:8443"
    networks:
      - qnap-apps

  minimal-notebook:
    image: jupyter/minimal-notebook:notebook-6.5.1
    container_name: qnap-minimal-notebook
    hostname: minimal-notebook
    command: start-notebook.sh --NotebookApp.password=${JUPYTER_NOTEBOOK_PASSWORD:?error}
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
      - PUID=1000
      - PGID=1000
      - JUPYTER_ENABLE_LAB=yes
      - GRANT_SUDO=yes
    volumes:
      - /share/Container/minimal-notebook:/home/jovyan/work
    ports:
      - "28888:8888"
    networks:
      - qnap-apps

  jumpserver:
    image: jumpserver/jms_all:v2.27.0
    container_name: qnap-jms
    hostname: jms
    restart: always
    privileged: true
    environment:
      - SECRET_KEY=${JMS_SECRET_KEY:?error}
      - BOOTSTRAP_TOKEN=${JMS_BOOTSTRAP_TOKEN:?error}
      - LOG_LEVEL=ERROR
      - DB_HOST=mysql-main
      - DB_PORT=3306
      - DB_USER=jumpserver
      - DB_PASSWORD=${JMS_DB_PASSWORD:?error}
      - DB_NAME=jumpserver
      - REDIS_HOST=master
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD:?error}
      - MAGNUS_PORTS=40000-40100
    volumes:
      - /share/Container/jumpserver/core/data:/opt/jumpserver/data
      - /share/Container/jumpserver/koko/data:/opt/koko/data
      - /share/Container/jumpserver/lion/data:/opt/lion/data
    ports:
      - "28090:80"
      - "2222:2222"
      - "3389:3389"
      - "40000-40100:40000-40100"
    depends_on:
      - mysql-main
      - master
    networks:
      - qnap-apps

# ------------------------------------------------------- Minio -------------------------------------------------------

  minio:
    image: minio/minio:RELEASE.2022-10-24T18-35-07Z
    container_name: qnap-minio
    hostname: minio
    restart: always
    command: server /data --address ":29000" --console-address ":29001"
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:?error}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:?error}
    volumes:
      - /share/Container/minio:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "29000:29000"
      - "29001:29001"
    networks:
      - qnap-apps

# ------------------------------------------------------ Registry ------------------------------------------------------

  registry-frontend:  # Registry WebUI
    image: konradkleine/docker-registry-frontend:v2
    container_name: qnap-registry-web
    hostname: registry-web
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
      - ENV_DOCKER_REGISTRY_HOST=${NAS_DOMAIN:?error}
      - ENV_DOCKER_REGISTRY_PORT=5000
    ports:
      - "28092:80"
    depends_on:
      - registry-backend
    networks:
      - qnap-apps

  registry-backend:  # Registry Server
    image: registry:2
    container_name: qnap-registry
    hostname: registry
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
    volumes:
      - /share/Container/registry:/var/lib/registry
    ports:
      - "5000:5000"
    networks:
      - qnap-apps

# ------------------------------------------------------- MySQL -------------------------------------------------------

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2
    container_name: qnap-phpmyadmin
    hostname: phpmyadmin
    restart: always
    environment:
      - PMA_HOSTS=mysql-main,mysql-replica
      - PMA_PORT=3306
    ports:
      - "9080:80"
    depends_on:
      - mysql-main
      - mysql-replica
    networks:
      - qnap-apps

  mysql-main:
    image: mysql:8
    container_name: qnap-mysql-main
    hostname: mysql-main
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --server-id=100
    ports:
      - "3306:3306"
    volumes:
      - /share/Container/mysql/main:/var/lib/mysql
      - /share/Container/mysql/conf/main:/etc/mysql/conf.d:ro
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:?error}
    networks:
      - qnap-apps

  mysql-replica:
    image: mysql:8
    container_name: qnap-mysql-replica
    hostname: mysql-replica
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --server-id=101
    ports:
      - "3307:3306"
    volumes:
      - /share/Container/mysql/replica:/var/lib/mysql
      - /share/Container/mysql/conf/replica:/etc/mysql/conf.d:ro
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:?error}
    networks:
      - qnap-apps

# ------------------------------------------------------- Redis -------------------------------------------------------

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: qnap-redis-commander
    hostname: redis-commander
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
      - REDIS_HOSTS=master:master:6379:0:${REDIS_PASSWORD:?error},slave1:slave1:6379:0:${REDIS_PASSWORD:?error},slave2:slave2:6379:0:${REDIS_PASSWORD:?error}  # 密码参考master配置
    ports:
      - "9081:8081"
    depends_on:
      - master
      - slave1
      - slave2
      - sentinel1
      - sentinel2
      - sentinel3
    networks:
      - qnap-apps

  master:
    image: redis:6
    container_name: qnap-redis-master
    hostname: redis-master
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD:?error} --appendonly yes  # 随机密码（可按需修改）
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
    volumes:
      - /share/Container/redis/master:/data
    ports:
      - "6379:6379"
    networks:
      - qnap-apps

  slave1:
    image: redis:6
    container_name: qnap-redis-slave-1
    hostname: redis-slave-1
    restart: always
    command: redis-server --replicaof master 6379 --requirepass ${REDIS_PASSWORD:?error} --masterauth ${REDIS_PASSWORD:?error} --appendonly yes  # 密码参考master配置
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
    volumes:
      - /share/Container/redis/slave1:/data
    ports:
      - "6381:6379"
    depends_on:
      - master
    networks:
      - qnap-apps

  slave2:
    image: redis:6
    container_name: qnap-redis-slave-2
    hostname: redis-slave-2
    restart: always
    command: redis-server --replicaof master 6379 --requirepass ${REDIS_PASSWORD:?error} --masterauth ${REDIS_PASSWORD:?error} --appendonly yes  # 密码参考master配置
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
    volumes:
      - /share/Container/redis/slave2:/data
    ports:
      - "6382:6379"
    depends_on:
      - master
    networks:
      - qnap-apps

  sentinel1:
    image: redis:6
    container_name: qnap-redis-sentinel-1
    hostname: redis-sentinel-1
    restart: always
    command: ["redis-sentinel", "/usr/local/etc/redis/redis-sentinel.conf"]
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
    volumes:
      - /share/Container/redis/redis-sentinel-1.conf:/usr/local/etc/redis/redis-sentinel.conf
    depends_on:
      - master
    networks:
      - qnap-apps

  sentinel2:
    image: redis:6
    container_name: qnap-redis-sentinel-2
    hostname: redis-sentinel-2
    restart: always
    command: ["redis-sentinel", "/usr/local/etc/redis/redis-sentinel.conf"]
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
    volumes:
      - /share/Container/redis/redis-sentinel-2.conf:/usr/local/etc/redis/redis-sentinel.conf
    depends_on:
      - slave1
    networks:
      - qnap-apps

  sentinel3:
    image: redis:6
    container_name: qnap-redis-sentinel-3
    hostname: redis-sentinel-3
    restart: always
    command: ["redis-sentinel", "/usr/local/etc/redis/redis-sentinel.conf"]
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
    volumes:
      - /share/Container/redis/redis-sentinel-3.conf:/usr/local/etc/redis/redis-sentinel.conf
    depends_on:
      - slave2
    networks:
      - qnap-apps
