version: "3"

networks:
  qnap-apps:
    driver: bridge

services:

  portainer:  # Container Management UI
    image: portainer/portainer-ce:2.15.1
    container_name: qnap-portainer
    hostname: portainer
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
    volumes:
      - /share/Container/portainer:/data  # Should be changed !!!
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8000:8000"  # TCP Tunnel (Server)
      - "9000:9000"  # HTTP
      - "9443:9443"  # HTTPS
    networks:
      - qnap-apps

# ------------------------------------------------------ Registry ------------------------------------------------------

  registry-frontend:  # Registry WebUI
    image: konradkleine/docker-registry-frontend:v2
    container_name: qnap-registry-web
    hostname: registry-web
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
      - ENV_DOCKER_REGISTRY_HOST=registry
      - ENV_DOCKER_REGISTRY_PORT=5000
    ports:
      - "9082:80"
    depends_on:
      - registry-backend
    networks:
      - qnap-apps

  registry-backend:  # Registry Server
    image: registry:2
    container_name: qnap-registry
    hostname: registry
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
    volumes:  # Should be changed !!!
      - /share/Container/registry:/var/lib/registry
    ports:
      - "5000:5000"
    networks:
      - qnap-apps

# ------------------------------------------------------- MySQL -------------------------------------------------------

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2
    container_name: qnap-phpmyadmin
    hostname: phpmyadmin
    restart: always
    environment:
      - PMA_HOSTS=mysql-main,mysql-replica
      - PMA_PORT=3306
    ports:
      - "9080:80"
    depends_on:
      - mysql-main
      - mysql-replica
    networks:
      - qnap-apps

  mysql-main:
    image: mysql:8
    container_name: qnap-mysql-main
    hostname: mysql-main
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --server-id=100
    ports:
      - "3306:3306"
    volumes:
      - /share/Container/mysql/main:/var/lib/mysql
      - /share/Container/mysql/conf/main:/etc/mysql/conf.d:ro
    environment:
      - MYSQL_ROOT_PASSWORD=wZ6try8MCNGi6n8P  # 随机密码（可按需修改）
    networks:
      - qnap-apps

  mysql-replica:
    image: mysql:8
    container_name: qnap-mysql-replica
    hostname: mysql-replica
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --server-id=101
    ports:
      - "3307:3306"
    volumes:
      - /share/Container/mysql/replica:/var/lib/mysql
      - /share/Container/mysql/conf/replica:/etc/mysql/conf.d:ro
    environment:
      - MYSQL_ROOT_PASSWORD=wZ6try8MCNGi6n8P  # 随机密码（可按需修改）
    networks:
      - qnap-apps

# ------------------------------------------------------- Redis -------------------------------------------------------

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: qnap-redis-commander
    hostname: redis-commander
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
      - REDIS_HOSTS=master:master:6379:0:kyUQ9xf7knPbYCQt,slave1:slave1:6379:0:kyUQ9xf7knPbYCQt,slave2:slave2:6379:0:kyUQ9xf7knPbYCQt
    ports:
      - "9081:8081"
    depends_on:
      - master
      - slave1
      - slave2
      - sentinel1
      - sentinel2
      - sentinel3
    networks:
      - qnap-apps

  master:
    image: redis:6
    container_name: qnap-redis-master
    hostname: redis-master
    restart: always
    command: redis-server --requirepass kyUQ9xf7knPbYCQt --appendonly yes
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
    volumes:
      - /share/Container/redis/master:/data
    ports:
      - "6379:6379"
    networks:
      - qnap-apps

  slave1:
    image: redis:6
    container_name: qnap-redis-slave-1
    hostname: redis-slave-1
    restart: always
    command: redis-server --replicaof master 6379 --requirepass kyUQ9xf7knPbYCQt --masterauth kyUQ9xf7knPbYCQt --appendonly yes
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
    volumes:
      - /share/Container/redis/slave1:/data
    ports:
      - "6381:6379"
    depends_on:
      - master
    networks:
      - qnap-apps

  slave2:
    image: redis:6
    container_name: qnap-redis-slave-2
    hostname: redis-slave-2
    restart: always
    command: redis-server --replicaof master 6379 --requirepass kyUQ9xf7knPbYCQt --masterauth kyUQ9xf7knPbYCQt --appendonly yes
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
    volumes:
      - /share/Container/redis/slave2:/data
    ports:
      - "6382:6379"
    depends_on:
      - master
    networks:
      - qnap-apps

  sentinel1:
    image: redis:6
    container_name: qnap-redis-sentinel-1
    hostname: redis-sentinel-1
    restart: always
    command: ["redis-sentinel", "/usr/local/etc/redis/redis-sentinel.conf"]
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
    volumes:
      - /share/Container/redis/redis-sentinel-1.conf:/usr/local/etc/redis/redis-sentinel.conf
    depends_on:
      - master
    networks:
      - qnap-apps

  sentinel2:
    image: redis:6
    container_name: qnap-redis-sentinel-2
    hostname: redis-sentinel-2
    restart: always
    command: ["redis-sentinel", "/usr/local/etc/redis/redis-sentinel.conf"]
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
    volumes:
      - /share/Container/redis/redis-sentinel-2.conf:/usr/local/etc/redis/redis-sentinel.conf
    depends_on:
      - slave1
    networks:
      - qnap-apps

  sentinel3:
    image: redis:6
    container_name: qnap-redis-sentinel-3
    hostname: redis-sentinel-3
    restart: always
    command: ["redis-sentinel", "/usr/local/etc/redis/redis-sentinel.conf"]
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
    volumes:
      - /share/Container/redis/redis-sentinel-3.conf:/usr/local/etc/redis/redis-sentinel.conf
    depends_on:
      - slave2
    networks:
      - qnap-apps
