version: "3"

networks:
  qnap-apps:
    driver: bridge

services:

  portainer:  # Container Management UI
    image: portainer/portainer-ce:2.15.1
    container_name: qnap-portainer
    hostname: portainer
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
    volumes:
      - /share/Container/portainer:/data  # Should be changed !!!
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8000:8000"  # TCP Tunnel (Server)
      - "9000:9000"  # HTTP
      - "9443:9443"  # HTTPS
    networks:
      - qnap-apps

  nextcloud:  # Private Cloud Disk
    image: nextcloud:24-apache
    container_name: qnap-nextcloud
    hostname: nextcloud
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
      - USER_UID=1000
      - USER_GID=1000
    volumes:  # Should be changed !!!
      - /share/Container/nextcloud/nextcloud:/var/www/html
      - /share/Container/nextcloud/apps:/var/www/html/custom_apps
      - /share/Container/nextcloud/config:/var/www/html/config
      - /share/Container/nextcloud/data:/var/www/html/data
      - /share/Container/nextcloud/theme:/var/www/html/themes/custom
      - /share/Cloud:/media/qnap
    ports:
      - "9086:80"  # HTTP
    links:
      - mysql-main
    depends_on:
      - mysql-main
    networks:
      - qnap-apps

  jellyfin:  # Free Software Media System
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: qnap-jellyfin
    hostname: jellyfin
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
      - PUID=1000
      - PGID=1000
      - JELLYFIN_PublishedServerUrl=qnap.liukun.com
    volumes:  # Should be changed !!!
      - /share/Container/jellyfin/library:/config
      - /share/Container/jellyfin/tvseries:/data/tvshows
      - /share/Public/Media:/data/movies
    ports:
      - "8096:8096"
      - "8920:8920"
      - "7359:7359/udp"
      - "1900:1900/udp"
    networks:
      - qnap-apps

  piwigo:  # Photo Gallery
    image: lscr.io/linuxserver/piwigo:latest
    container_name: qnap-piwigo
    hostname: piwigo
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
      - PUID=1000
      - PGID=1000
    volumes:  # Should be changed !!!
      - /share/Container/piwigo/config:/config
      - /share/Container/piwigo/gallery:/gallery
      - /share/Cloud/Gallery:/gallery/galleries
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "9085:80"
    depends_on:
      - mysql-main
    networks:
      - qnap-apps

  gitea:
    image: gitea/gitea:1.17.3
    container_name: qnap-gitea
    hostname: gitea
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
      - USER_UID=1000
      - USER_GID=1000
    volumes:  # Should be changed !!!
      - /share/Container/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "9084:3000"
      - "10022:22"
    depends_on:
      - mysql-main
    networks:
      - qnap-apps

# ------------------------------------------------------- Minio -------------------------------------------------------

  minio:
    image: minio/minio:RELEASE.2022-10-24T18-35-07Z
    container_name: qnap-minio
    hostname: minio
    restart: always
    command: server /data --address ":9000" --console-address ":9001"
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
      - MINIO_ROOT_USER=LehXBoVThyyDU3vZ
      - MINIO_ROOT_PASSWORD=Ggi057AOL8ZRrvxv
    volumes:  # Should be changed !!!
      - /share/Container/minio:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "9083:9000"
      - "9001:9001"
    networks:
      - qnap-apps

# ------------------------------------------------------ Registry ------------------------------------------------------

  registry-frontend:  # Registry WebUI
    image: konradkleine/docker-registry-frontend:v2
    container_name: qnap-registry-web
    hostname: registry-web
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
      - ENV_DOCKER_REGISTRY_HOST=qnap.liukun.com
      - ENV_DOCKER_REGISTRY_PORT=5000
    ports:
      - "9082:80"
    depends_on:
      - registry-backend
    networks:
      - qnap-apps

  registry-backend:  # Registry Server
    image: registry:2
    container_name: qnap-registry
    hostname: registry
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
    volumes:  # Should be changed !!!
      - /share/Container/registry:/var/lib/registry
    ports:
      - "5000:5000"
    networks:
      - qnap-apps

# ------------------------------------------------------- MySQL -------------------------------------------------------

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2
    container_name: qnap-phpmyadmin
    hostname: phpmyadmin
    restart: always
    environment:
      - PMA_HOSTS=mysql-main,mysql-replica
      - PMA_PORT=3306
    ports:
      - "9080:80"
    depends_on:
      - mysql-main
      - mysql-replica
    networks:
      - qnap-apps

  mysql-main:
    image: mysql:8
    container_name: qnap-mysql-main
    hostname: mysql-main
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --server-id=100
    ports:
      - "3306:3306"
    volumes:
      - /share/Container/mysql/main:/var/lib/mysql
      - /share/Container/mysql/conf/main:/etc/mysql/conf.d:ro
    environment:
      - MYSQL_ROOT_PASSWORD=wZ6try8MCNGi6n8P  # 随机密码（可按需修改）
    networks:
      - qnap-apps

  mysql-replica:
    image: mysql:8
    container_name: qnap-mysql-replica
    hostname: mysql-replica
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --server-id=101
    ports:
      - "3307:3306"
    volumes:
      - /share/Container/mysql/replica:/var/lib/mysql
      - /share/Container/mysql/conf/replica:/etc/mysql/conf.d:ro
    environment:
      - MYSQL_ROOT_PASSWORD=wZ6try8MCNGi6n8P  # 随机密码（可按需修改）
    networks:
      - qnap-apps

# ------------------------------------------------------- Redis -------------------------------------------------------

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: qnap-redis-commander
    hostname: redis-commander
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
      - REDIS_HOSTS=master:master:6379:0:kyUQ9xf7knPbYCQt,slave1:slave1:6379:0:kyUQ9xf7knPbYCQt,slave2:slave2:6379:0:kyUQ9xf7knPbYCQt
    ports:
      - "9081:8081"
    depends_on:
      - master
      - slave1
      - slave2
      - sentinel1
      - sentinel2
      - sentinel3
    networks:
      - qnap-apps

  master:
    image: redis:6
    container_name: qnap-redis-master
    hostname: redis-master
    restart: always
    command: redis-server --requirepass kyUQ9xf7knPbYCQt --appendonly yes
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
    volumes:
      - /share/Container/redis/master:/data
    ports:
      - "6379:6379"
    networks:
      - qnap-apps

  slave1:
    image: redis:6
    container_name: qnap-redis-slave-1
    hostname: redis-slave-1
    restart: always
    command: redis-server --replicaof master 6379 --requirepass kyUQ9xf7knPbYCQt --masterauth kyUQ9xf7knPbYCQt --appendonly yes
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
    volumes:
      - /share/Container/redis/slave1:/data
    ports:
      - "6381:6379"
    depends_on:
      - master
    networks:
      - qnap-apps

  slave2:
    image: redis:6
    container_name: qnap-redis-slave-2
    hostname: redis-slave-2
    restart: always
    command: redis-server --replicaof master 6379 --requirepass kyUQ9xf7knPbYCQt --masterauth kyUQ9xf7knPbYCQt --appendonly yes
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
    volumes:
      - /share/Container/redis/slave2:/data
    ports:
      - "6382:6379"
    depends_on:
      - master
    networks:
      - qnap-apps

  sentinel1:
    image: redis:6
    container_name: qnap-redis-sentinel-1
    hostname: redis-sentinel-1
    restart: always
    command: ["redis-sentinel", "/usr/local/etc/redis/redis-sentinel.conf"]
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
    volumes:
      - /share/Container/redis/redis-sentinel-1.conf:/usr/local/etc/redis/redis-sentinel.conf
    depends_on:
      - master
    networks:
      - qnap-apps

  sentinel2:
    image: redis:6
    container_name: qnap-redis-sentinel-2
    hostname: redis-sentinel-2
    restart: always
    command: ["redis-sentinel", "/usr/local/etc/redis/redis-sentinel.conf"]
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
    volumes:
      - /share/Container/redis/redis-sentinel-2.conf:/usr/local/etc/redis/redis-sentinel.conf
    depends_on:
      - slave1
    networks:
      - qnap-apps

  sentinel3:
    image: redis:6
    container_name: qnap-redis-sentinel-3
    hostname: redis-sentinel-3
    restart: always
    command: ["redis-sentinel", "/usr/local/etc/redis/redis-sentinel.conf"]
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
    volumes:
      - /share/Container/redis/redis-sentinel-3.conf:/usr/local/etc/redis/redis-sentinel.conf
    depends_on:
      - slave2
    networks:
      - qnap-apps
